# Generated by Django 4.0 on 2022-01-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEapp1', '0002_contact_info_user_password_alter_contact_info_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=40)),
                ('admin_password', models.CharField(max_length=40)),
            ],
        ),
    ]
