# Generated by Django 4.0 on 2022-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEapp1', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_info',
            name='user_password',
            field=models.CharField(max_length=255),
        ),
    ]
